# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vWT6rQnT8IPTDIh9_guNkNBtgejiHZiD

LUAS SEGITIGA
"""

# Input alas dan tinggi segitiga
alas = float(input("Masukkan panjang alas segitiga: "))
tinggi = float(input("Masukkan tinggi segitiga: "))

# Menghitung luas segitiga
luas = 0.5 * alas * tinggi

# Output luas segitiga
print("Luas segitiga adalah:", luas)