# -*- coding: utf-8 -*-
"""Volume Bola.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hz48-ENkhwKd3UPxB_tzLZIXh3mLSavQ

Volume Bola
"""

import math

# Input jari-jari bola
jari_jari = float(input("Masukkan jari-jari bola: "))

# Menghitung volume bola
volume = (4/3) * math.pi * jari_jari**3

# Output volume bola
print("Volume bola adalah:", volume)