# -*- coding: utf-8 -*-
"""VolumeBalok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xBzDlgL-3P6BLr3FcFCOn-daWTO3_1Gl

Volume Balok
"""

# Input panjang, lebar, dan tinggi balok
panjang = float(input("Masukkan panjang balok: "))
lebar = float(input("Masukkan lebar balok: "))
tinggi = float(input("Masukkan tinggi balok: "))

# Menghitung volume balok
volume = panjang * lebar * tinggi

# Output volume balok
print("Volume balok adalah:", volume)